services:
  web:
    image: httpd:2.4
    ports:
      - "9000:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs

  api:
    build: ./backend/build/python
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    depends_on:
      - mysql

  mysql:
    build: ./backend/build/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
